### ISSUE TITLE
Don't find the API key

### ISSUE THREAD

**Issue by jibe-b** [OAButton/odb#61]
Hi there,

I (re) created an OAButton account but I can't find the API key in order to use the Firefox addon.

My "account page" looks like this

![oabutton-fullpage](https://cloud.githubusercontent.com/assets/6146483/21270220/f5de908e-c3b5-11e6-8247-f6691c920acc.png)

and in the source of the webpage there are stufff done with the API key but that's not clear to me.

**Comment by JosephMcArthur** [comment]
Hi jibe, thanks so much for getting in touch.

This will be happening because our new release will grab the key
automatically from the page - but isn't out yet (delays in review). There
is a bookmarklet on the page that you should be able to use. Let me know if
that works for you.

Thanks,

Joe
On Fri, 16 Dec 2016, 4:37 p.m. jibe-b, <notifications@github.com> wrote:

Hi there,

I (re) created an OAButton account but I can't find the API key in order to
use the Firefox addon.

My "account page" looks like this

[image: oabutton-fullpage]
<https://cloud.githubusercontent.com/assets/6146483/21270220/f5de908e-c3b5-11e6-8247-f6691c920acc.png>

and in the source of the webpage there are stufff done with the API key but
that's not clear to me.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/OAButton/odb/issues/61>, or mute the thread

**Comment by jibe-b** [comment]
Thanks for your answer. I could get a newer version of the bookmarklet.

An apikey is stored in this bookmarklet but when I try it in the extension, it doesn't work.

For the moment I can make use of the OAbutton so it's fine, I just hope the extension will be working soon too.

**Comment by JosephMcArthur** [comment]
If you send me your email (joe@righttoresearch.org) I'll send you a note when it's released!

**Comment by jibe-b** [comment]
Status (firefox 50 on Linux):

The bookmark works fine but the Firefox extension still doesn''t find the API key by itself, nor does anything happen when I enter the API key available in clear /!\ in the bookmark.

The bookmark works fine.

**Comment by JosephMcArthur** [comment]
This is likely because we still haven't shipped the FF add-on (nearly there). You're still on my list to to notify as soon as it's out!
